### PR TITLE
Add Ruby support

### PR DESCRIPTION
**Pull request by tradiff**

### CODE REVIEW

**Comment by rareitems** [comment]
Thank you, but from a quick test it doesn't seem like it print on the same  line, any reason why didn't you something like this to print it on the same line?
```
ruby = function(inside, variable)
    return string.format('pp "%s = #{%s}"', inside, variable)
end,
```

**Comment by tradiff** [comment]
Updated to use a single line. You're right, that is more in line with the other languages you have here.

The difference is if the object being printed is a primitive object or complex object. For primitives, what you said works better (1 line). But for a complex object, casting the object to a string will only print the class name and object id. Whereas my separated code would have printed out all of the object's properties. BTW now that we're printing a single string, there's no benefit to 'pp'. So i've also changed to `puts`, because `pp` would have wrapped the output in quote marks.

**Comment by rareitems** [comment]
Sorry but could you revert the update? The double line but actually print out the the value of a complex object seems a lot more useful than one line and some data in 99% cases person using the plugin won't except and doesn't want.

**Comment by tradiff** [comment]
@rareitems ok, done 😄

**Comment by rareitems** [comment]
Thanks

**Pull request merged**
